name: Build and Deploy to Raspberry Pi

on:
  push:
    branches: [main]

jobs:
  deploy-on-pi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code (for workflow context)
        uses: actions/checkout@v4

      - name: SSH: Pull latest code
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PI_HOST }}
          port: ${{ secrets.PI_PORT }}
          username: ${{ secrets.PI_USER }}
          key: ${{ secrets.PI_SSH_KEY }}
          script: |
            set -e
            cd ~/rust-readme-chess
            git pull

      - name: SSH: Clean build artifacts
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PI_HOST }}
          port: ${{ secrets.PI_PORT }}
          username: ${{ secrets.PI_USER }}
          key: ${{ secrets.PI_SSH_KEY }}
          script: |
            set -e
            cd ~/rust-readme-chess
            source $HOME/.cargo/env
            cargo clean

      - name: SSH: Update dependencies
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PI_HOST }}
          port: ${{ secrets.PI_PORT }}
          username: ${{ secrets.PI_USER }}
          key: ${{ secrets.PI_SSH_KEY }}
          script: |
            set -e
            cd ~/rust-readme-chess
            source $HOME/.cargo/env
            cargo update

      - name: SSH: Build release
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PI_HOST }}
          port: ${{ secrets.PI_PORT }}
          username: ${{ secrets.PI_USER }}
          key: ${{ secrets.PI_SSH_KEY }}
          script: |
            set -e
            cd ~/rust-readme-chess
            source $HOME/.cargo/env
            cargo build --release

      - name: SSH: Strip binary
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PI_HOST }}
          port: ${{ secrets.PI_PORT }}
          username: ${{ secrets.PI_USER }}
          key: ${{ secrets.PI_SSH_KEY }}
          script: |
            set -e
            cd ~/rust-readme-chess
            strip target/release/rust_readme_chess || true

      - name: SSH: Restart service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PI_HOST }}
          port: ${{ secrets.PI_PORT }}
          username: ${{ secrets.PI_USER }}
          key: ${{ secrets.PI_SSH_KEY }}
          script: |
            sudo systemctl restart rust-readme-chess
            sudo systemctl status rust-readme-chess --no-pager
