name: Build and Deploy to Raspberry Pi

on:
  push:
    branches: [main]

jobs:
  deploy-on-pi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code (for workflow context)
        uses: actions/checkout@v4

      - name: Pull latest code, clean, update, build, and strip on Raspberry Pi
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PI_HOST }}
          port: ${{ secrets.PI_PORT }}
          username: ${{ secrets.PI_USER }}
          key: ${{ secrets.PI_SSH_KEY }}
          script: |
            set -e
            cd ~/rust-readme-chess
            git pull
            cargo clean
            cargo update
            cargo build --release
            strip target/release/rust_readme_chess || true
            sudo systemctl restart rust-readme-chess
            sudo systemctl status rust-readme-chess --no-pager
