name: Build and Deploy to Raspberry Pi

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clean previous builds
        run: cargo clean

      - name: Update dependencies
        run: cargo update

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install ARM toolchain
        run: sudo apt-get update && sudo apt-get install -y gcc-arm-linux-gnueabihf

      - name: Add ARM target
        run: rustup target add armv7-unknown-linux-gnueabihf

      - name: Build release for ARM
        run: cargo build --release --target=armv7-unknown-linux-gnueabihf

      - name: Strip binary
        run: arm-linux-gnueabihf-strip target/armv7-unknown-linux-gnueabihf/release/rust_readme_chess

      - name: Copy binary to Raspberry Pi
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.PI_HOST }}
          port: ${{ secrets.PI_PORT }}
          username: ${{ secrets.PI_USER }}
          key: ${{ secrets.PI_SSH_KEY }}
          source: target/armv7-unknown-linux-gnueabihf/release/rust_readme_chess
          target: /home/grim/rust-readme-chess/

      - name: Restart service on Raspberry Pi
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PI_HOST }}
          port: ${{ secrets.PI_PORT }}
          username: ${{ secrets.PI_USER }}
          key: ${{ secrets.PI_SSH_KEY }}
          script: |
            sudo systemctl restart rust-readme-chess
            sudo systemctl status rust-readme-chess --no-pager
